Ext.define('Bar.store.Prefs', {
    extend: 'Ext.data.Store',
    config: {
        model: 'Bar.model.Pref',
        data: [
            {id:'01', pref: '北海道'},
            {id:'02', pref: '青森県'},
            {id:'03', pref: '岩手県'},
            {id:'04', pref: '宮城県'},
            {id:'05', pref: '秋田県'},
            {id:'06', pref: '山形県'},
            {id:'07', pref: '福島県'},
            {id:'08', pref: '茨城県'},
            {id:'09', pref: '栃木県'},
            {id:'10', pref: '群馬県'},
            {id:'11', pref: '埼玉県'},
            {id:'12', pref: '千葉県'},
            {id:'13', pref: '東京都'},
            {id:'14', pref: '神奈川県'},
            {id:'15', pref: '新潟県'},
            {id:'16', pref: '富山県'},
            {id:'17', pref: '石川県'},
            {id:'18', pref: '福井県'},
            {id:'19', pref: '山梨県'},
            {id:'20', pref: '長野県'},
            {id:'21', pref: '岐阜県'},
            {id:'22', pref: '静岡県'},
            {id:'23', pref: '愛知県'},
            {id:'24', pref: '三重県'},
            {id:'25', pref: '滋賀県'},
            {id:'26', pref: '京都府'},
            {id:'27', pref: '大阪府'},
            {id:'28', pref: '兵庫県'},
            {id:'29', pref: '奈良県'},
            {id:'30', pref: '和歌山県'},
            {id:'31', pref: '鳥取県'},
            {id:'32', pref: '島根県'},
            {id:'33', pref: '岡山県'},
            {id:'34', pref: '広島県'},
            {id:'35', pref: '山口県'},
            {id:'36', pref: '徳島県'},
            {id:'37', pref: '香川県'},
            {id:'38', pref: '愛媛県'},
            {id:'39', pref: '高知県'},
            {id:'40', pref: '福岡県'},
            {id:'41', pref: '佐賀県'},
            {id:'42', pref: '長崎県'},
            {id:'43', pref: '熊本県'},
            {id:'44', pref: '大分県'},
            {id:'45', pref: '宮崎県'},
            {id:'46', pref: '鹿児島県'},
            {id:'47', pref: '沖縄県'}
        ]
    }
});
